apiVersion: policy.mcm.ibm.com/v1alpha1
kind: Policy
metadata:
  name: policy-auditpolicy-1
  namespace: mcm-policies
  annotations:
    policy.mcm.ibm.com/categories: PR.PT Protective Technology
    policy.mcm.ibm.com/controls: PR.PT-1 Audit Logging
    policy.mcm.ibm.com/standards: NIST-CSF
    seed-generation: '6'
  finalizers:
    - propagator.finalizer.mcm.ibm.com
  generation: 212
  resourceVersion: '51493186'
spec:
  complianceType: musthave
  disabled: false
  namespaces:
    exclude:
      - kube-*
    include:
      - default
  policy-templates:
    - objectDefinition:
        apiVersion: audit.policies.ibm.com/v1alpha1
        kind: AuditPolicy
        metadata:
          name: policy-auditpolicy-1-example
        spec:
          clusterAuditPolicy:
            auditPolicyRules:
              auth-idp: validate
              helmapi: ignore
              kubernetes: ignore
              platform-api: ignore
              platform-identity-manager: validate
              platform-identity-provider: validate
              vulnerability-advisor: ignore
          namespaceSelector:
            exclude:
              - kube-system
            include:
              - default
              - kube-*
          remediationAction: inform
          severity: low
  remediationAction: inform
